In [1]:
import pandas as pd
import numpy as np

In [57]:
df1 = pd.read_csv("data.csv")
df2 = pd.read_csv("data2.csv")
df1.head()

        Date    title       category       account amount     type
0  8/11/2024  Karthik   Bills & Fees  Savings Bank     45  EXPENSE
1  8/10/2024    Juice  Food & Drinks          Cash     40  EXPENSE
2   8/9/2024     Tire      Transport          Cash     10  EXPENSE
3   8/7/2024     Baba   Bills & Fees  Savings Bank    200  EXPENSE
4   8/4/2024   Reward   Bills & Fees   Salary Bank      4   INCOME

In [59]:
df1.shape

(1155, 6)

In [61]:
df2.shape

(1222, 5)

In [63]:
df1.columns

Index(['Date', 'title', 'category', 'account', 'amount', 'type'], dtype='object')

In [65]:
df2.columns

Index(['1/2/2020', 'Score each.', 'Food & Drink', '1485.69', 'Expense'], dtype='object')

In [67]:
df2.columns = ['Date' , 'title', 'category', 'amount' , 'type']
df2.head()

,Date,title,category,amount,type
0,1/2/2020,Quality throughout.,Utilities,1475.58,Expense
1,1/4/2020,Instead ahead despite measure ago.,Rent,1185.08,Expense
2,NaN,NaN,NaN,NaN,NaN
3,1/13/2020,Future choice whatever from.,Food & Drink,1126.88,Expense
4,1/14/2020,Benefit suggest page southern.,Shopping,448.68,Expense

In [31]:
df2 = df2.dropna()
df2.head()

,Date,title,category,amount,type
0,1/2/2020,Quality throughout.,Utilities,1475.58,Expense
1,1/4/2020,Instead ahead despite measure ago.,Rent,1185.08,Expense
3,1/13/2020,Future choice whatever from.,Food & Drink,1126.88,Expense
4,1/14/2020,Benefit suggest page southern.,Shopping,448.68,Expense
5,1/18/2020,By two bad fall pick.,Food & Drink,1520.03,Expense

In [69]:
df1 = df1.drop(columns=['account'])
df1.head()

        Date    title       category amount     type
0  8/11/2024  Karthik   Bills & Fees     45  EXPENSE
1  8/10/2024    Juice  Food & Drinks     40  EXPENSE
2   8/9/2024     Tire      Transport     10  EXPENSE
3   8/7/2024     Baba   Bills & Fees    200  EXPENSE
4   8/4/2024   Reward   Bills & Fees      4   INCOME

In [71]:
df = pd.concat([df1, df2])

In [73]:
df.shape

(2377, 5)

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2376 entries, 0 to 1221
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      2376 non-null   object
 1   title     2352 non-null   object
 2   category  2215 non-null   object
 3   amount    2376 non-null   object
 4   type      2376 non-null   object
dtypes: object(5)
memory usage: 111.4+ KB

In [75]:
df.isna()

       Date  title  category  amount   type
0     False  False     False   False  False
1     False  False     False   False  False
2     False  False     False   False  False
3     False  False     False   False  False
4     False  False     False   False  False
...     ...    ...       ...     ...    ...
1217  False  False     False   False  False
1218  False  False     False   False  False
1219  False  False     False   False  False
1220  False  False     False   False  False
1221  False  False     False   False  False

[2377 rows x 5 columns]

In [77]:
df = df.dropna()

In [79]:
df.Date.head()

0    8/11/2024
1    8/10/2024
2     8/9/2024
3     8/7/2024
4     8/4/2024
Name: Date, dtype: object

In [87]:
df = df[~df['type'].str.lower().eq('income')]
df.shape

(2151, 5)

In [89]:
df.tail()

            Date                     title          category  amount     type
1217  12/21/2024             Up hear draw.            Salary  784.35  Expense
1218  12/23/2024           Instead writer.  Health & Fitness  325.64  Expense
1219  12/28/2024            Quite as when.              Rent  514.09  Expense
1220  12/28/2024   Right analysis mention.     Entertainment  727.25  Expense
1221  12/29/2024  Discussion black follow.          Shopping  655.78  Expense

In [95]:

df.tail(

            Date                     title          category  amount
1217  12/21/2024             Up hear draw.            Salary  784.35
1218  12/23/2024           Instead writer.  Health & Fitness  325.64
1219  12/28/2024            Quite as when.              Rent  514.09
1220  12/28/2024   Right analysis mention.     Entertainment  727.25
1221  12/29/2024  Discussion black follow.          Shopping  655.78

In [101]:
df = df.drop(columns=['title', 'category'])
df.head()

        Date amount
0  8/11/2024     45
1  8/10/2024     40
2   8/9/2024     10
3   8/7/2024    200
5   8/4/2024    500

In [105]:
duplicates = df[df['Date'].duplicated()]
print(duplicates)

            Date   amount
7       8/2/2024      100
11      8/1/2024      500
13     7/31/2024      300
17     7/20/2024       50
21     7/14/2024       90
...          ...      ...
1202  11/24/2024   576.51
1203  11/24/2024   831.68
1205  11/25/2024    383.7
1216  12/19/2024  1047.07
1220  12/28/2024   727.25

[1073 rows x 2 columns]

In [107]:
# Step 1: Try converting amount column to numeric
df['amount'] = pd.to_numeric(df['amount'], errors='coerce')

# Step 2: Drop rows where amount became NaN (non-numeric ones)
df = df.dropna(subset=['amount'])

# Step 3: Optional - Reset index
df = df.reset_index(drop=True)

In [109]:
# Make sure Date is datetime (optional but good practice)
df['Date'] = pd.to_datetime(df['Date'])

# Group by Date and sum the amount
df = df.groupby('Date', as_index=False).agg({'amount': 'sum'})

# Optional: sort the dates
df = df.sort_values('Date').reset_index(drop=True)

In [111]:
df.shape

(1075, 2)

In [113]:
df.head()

        Date   amount
0 2020-01-02  1475.58
1 2020-01-04  1185.08
2 2020-01-13  1126.88
3 2020-01-14   448.68
4 2020-01-18  1520.03

In [115]:
df.tail()

           Date   amount
1070 2024-12-19  1453.44
1071 2024-12-21   784.35
1072 2024-12-23   325.64
1073 2024-12-28  1241.34
1074 2024-12-29   655.78

In [117]:
# 1. Ensure 'Date' column is datetime type
df['Date'] = pd.to_datetime(df['Date'])

# 2. Create the full range of dates from start to end
full_date_range = pd.date_range(start=df['Date'].min(), end=df['Date'].max(), freq='D')

# 3. Find missing dates
missing_dates = full_date_range.difference(df['Date'])

# 4. Print missing dates
print(missing_dates)

DatetimeIndex(['2020-01-03', '2020-01-05', '2020-01-06', '2020-01-07',
               '2020-01-08', '2020-01-09', '2020-01-10', '2020-01-11',
               '2020-01-12', '2020-01-15',
               ...
               '2024-12-13', '2024-12-14', '2024-12-17', '2024-12-18',
               '2024-12-20', '2024-12-22', '2024-12-24', '2024-12-25',
               '2024-12-26', '2024-12-27'],
              dtype='datetime64[ns]', length=749, freq=None)

In [123]:
missing_dates_df = pd.DataFrame(missing_dates, columns=['Missing Dates'])
missing_dates_df.to_csv('missing_dates.csv', index=False)

In [125]:
df.to_csv("final.csv", index = False )

In [141]:
df3 = pd.read_csv("new.csv")

In [143]:
# Step 2: Make sure both 'Date' columns are datetime type
df['Date'] = pd.to_datetime(df['Date'])
df3['Date'] = pd.to_datetime(df3['Date'])

# Step 3: Merge (concatenate) the two DataFrames
merged_df = pd.concat([df, df3])

# Step 4: Sort by Date
merged_df = merged_df.sort_values('Date').reset_index(drop=True)

In [145]:
merged_df.shape

(3650, 2)

In [147]:
merged_df.to_csv("finalData.csv", index = False )